### ISSUE TITLE
AttributeError: module 'bellows.config' has no attribute 'CONF_FLOW_CONTROL'

### ISSUE THREAD

**Issue by RonaldPhilipsen** [agners/silabs-flasher#4]
Hi, I recently installed silabs-flashed from scratch  but iḿ getting an issue in the setup:
this is on python 3.12.0 

```
/home/ronald245/.local/bin/silabs-flasher:81: SyntaxWarning: invalid escape sequence '\.'
  b"Gecko Bootloader v([0-9\.]*)\r\n"
Traceback (most recent call last):
  File "/home/ronald245/.local/bin/silabs-flasher", line 224, in <module>
    main()  # pylint: disable=no-value-for-parameter
    ^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ronald245/.local/bin/silabs-flasher", line 27, in inner
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ronald245/.local/bin/silabs-flasher", line 151, in info
    ezsp = await setup(ctx.obj["device"], ctx.obj["baudrate"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ronald245/.local/bin/silabs-flasher", line 36, in setup
    config.CONF_FLOW_CONTROL: config.CONF_FLOW_CONTROL_DEFAULT,
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bellows.config' has no attribute 'CONF_FLOW_CONTROL'

```

```
$ pip install silabs-flasher[gpio]
Defaulting to user installation because normal site-packages is not writeable
Collecting silabs-flasher[gpio]
  Downloading silabs_flasher-0.0.3-py3-none-any.whl (8.9 kB)
Collecting bellows (from silabs-flasher[gpio])
  Obtaining dependency information for bellows from https://files.pythonhosted.org/packages/e9/0d/d237f19102e9d95c5fd396f643f1e99a49cf929ecd897590685d61b8c280/bellows-0.37.1-py3-none-any.whl.metadata
  Downloading bellows-0.37.1-py3-none-any.whl.metadata (14 kB)
Collecting xmodem (from silabs-flasher[gpio])
  Obtaining dependency information for xmodem from https://files.pythonhosted.org/packages/8c/1a/e383b538450963953d4e652d2bce0a4cfbcf15ecc8c34ab998bd1329c95d/xmodem-0.4.7-py3-none-any.whl.metadata
  Downloading xmodem-0.4.7-py3-none-any.whl.metadata (4.3 kB)
Collecting pyserial (from silabs-flasher[gpio])
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 7.0 MB/s eta 0:00:00
Requirement already satisfied: click in /usr/lib/python3.12/site-packages (from silabs-flasher[gpio]) (8.1.3)
Requirement already satisfied: pexpect in /usr/lib/python3.12/site-packages (from silabs-flasher[gpio]) (4.8.0)
Collecting gpiod>=1.5.3 (from silabs-flasher[gpio])
  Downloading gpiod-2.1.3.tar.gz (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 15.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click-log>=0.2.1 (from bellows->silabs-flasher[gpio])
  Downloading click_log-0.4.0-py2.py3-none-any.whl (4.3 kB)
Collecting pure-pcapy3==1.0.1 (from bellows->silabs-flasher[gpio])
  Downloading pure-pcapy3-1.0.1.tar.gz (5.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting voluptuous (from bellows->silabs-flasher[gpio])
  Obtaining dependency information for voluptuous from https://files.pythonhosted.org/packages/12/44/2d0c03d9cc9edaed681842a441a9ab3e960b62adb172865692745fc9eff1/voluptuous-0.14.1-py3-none-any.whl.metadata
  Downloading voluptuous-0.14.1-py3-none-any.whl.metadata (20 kB)
Collecting zigpy>=0.60.0 (from bellows->silabs-flasher[gpio])
  Obtaining dependency information for zigpy>=0.60.0 from https://files.pythonhosted.org/packages/33/a8/bb9c5e73bc3b11de54e2121a0ee86345c7d84d41b44678150b0e737a8e71/zigpy-0.60.0-py3-none-any.whl.metadata
  Downloading zigpy-0.60.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: setuptools in /usr/lib/python3.12/site-packages (from pure-pcapy3==1.0.1->bellows->silabs-flasher[gpio]) (67.7.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.12/site-packages (from pexpect->silabs-flasher[gpio]) (0.7.0)
Collecting attrs (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 17.6 MB/s eta 0:00:00
Collecting aiohttp (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Obtaining dependency information for aiohttp from https://files.pythonhosted.org/packages/75/5f/90a2869ad3d1fb9bd984bfc1b02d8b19e381467b238bd3668a09faa69df5/aiohttp-3.9.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading aiohttp-3.9.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting aiosqlite>=0.16.0 (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Downloading aiosqlite-0.19.0-py3-none-any.whl (15 kB)
Collecting async-timeout (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Obtaining dependency information for async-timeout from https://files.pythonhosted.org/packages/a7/fa/e01228c2938de91d47b307831c62ab9e4001e747789d0b05baf779a6488c/async_timeout-4.0.3-py3-none-any.whl.metadata
  Downloading async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting crccheck (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Downloading crccheck-1.3.0-py3-none-any.whl (21 kB)
Collecting cryptography (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Obtaining dependency information for cryptography from https://files.pythonhosted.org/packages/62/bd/69628ab50368b1beb900eb1de5c46f8137169b75b2458affe95f2f470501/cryptography-41.0.7-cp37-abi3-manylinux_2_28_x86_64.whl.metadata
  Downloading cryptography-41.0.7-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Collecting typing-extensions (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting pyserial-asyncio (from zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Downloading pyserial_asyncio-0.6-py3-none-any.whl (7.6 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Downloading multidict-6.0.4.tar.gz (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 9.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting yarl<2.0,>=1.0 (from aiohttp->zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Obtaining dependency information for yarl<2.0,>=1.0 from https://files.pythonhosted.org/packages/1a/b1/78f142828d4bd97fc35616d8601d79fbce72adf44bf6eb7a750a1fcd15ff/yarl-1.9.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading yarl-1.9.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (28 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Downloading frozenlist-1.4.0.tar.gz (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.7/90.7 kB 19.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiosignal>=1.1.2 (from aiohttp->zigpy>=0.60.0->bellows->silabs-flasher[gpio])
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: cffi>=1.12 in /usr/lib64/python3.12/site-packages (from cryptography->zigpy>=0.60.0->bellows->silabs-flasher[gpio]) (1.15.1)
Requirement already satisfied: pycparser in /usr/lib/python3.12/site-packages (from cffi>=1.12->cryptography->zigpy>=0.60.0->bellows->silabs-flasher[gpio]) (2.20)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3.12/site-packages (from yarl<2.0,>=1.0->aiohttp->zigpy>=0.60.0->bellows->silabs-flasher[gpio]) (3.4)
Requirement already satisfied: ply==3.11 in /usr/lib/python3.12/site-packages (from pycparser->cffi>=1.12->cryptography->zigpy>=0.60.0->bellows->silabs-flasher[gpio]) (3.11)
Downloading bellows-0.37.1-py3-none-any.whl (233 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 22.3 MB/s eta 0:00:00
Downloading xmodem-0.4.7-py3-none-any.whl (35 kB)
Downloading zigpy-0.60.0-py3-none-any.whl (181 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.5/181.5 kB 29.8 MB/s eta 0:00:00
Downloading voluptuous-0.14.1-py3-none-any.whl (30 kB)
Downloading aiohttp-3.9.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 46.5 MB/s eta 0:00:00
Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Downloading cryptography-41.0.7-cp37-abi3-manylinux_2_28_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 72.7 MB/s eta 0:00:00
Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Downloading yarl-1.9.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (321 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 321.6/321.6 kB 58.9 MB/s eta 0:00:00
Building wheels for collected packages: gpiod, pure-pcapy3, frozenlist, multidict
  Building wheel for gpiod (pyproject.toml) ... done
  Created wheel for gpiod: filename=gpiod-2.1.3-cp312-cp312-linux_x86_64.whl size=38626 sha256=bb591b47794d47d3cd1aec8d8fc00b65b81bb67671f6e6aa6abe7571f7a87b4d
  Stored in directory: /home/ronald245/.cache/pip/wheels/8a/13/04/8e68bd59145932f356d3c020b23fa8f0eb69dcb7695ef9a448
  Building wheel for pure-pcapy3 (pyproject.toml) ... done
  Created wheel for pure-pcapy3: filename=pure_pcapy3-1.0.1-py3-none-any.whl size=5023 sha256=8483b8eddf8fc011fc491abff282beb1374b1fc1c9b8d6a580cebe8555aeafb1
  Stored in directory: /home/ronald245/.cache/pip/wheels/c6/d5/d3/d332db714e4a17584545fc5fdb953f966f2c78b7ce39e508b7
  Building wheel for frozenlist (pyproject.toml) ... done
  Created wheel for frozenlist: filename=frozenlist-1.4.0-cp312-cp312-linux_x86_64.whl size=62482 sha256=5114cfd17a66fd50e3feca93f15ac9edd3879a91618fa1ceacafea0e88c65cff
  Stored in directory: /home/ronald245/.cache/pip/wheels/f1/9c/94/9386cb0ea511a93226456388d41d35f1c24ba15a62ffd7b1ef
  Building wheel for multidict (pyproject.toml) ... done
  Created wheel for multidict: filename=multidict-6.0.4-cp312-cp312-linux_x86_64.whl size=34520 sha256=1d0cc96e06579181087d21819269fd59548737fbdcffc3b45d8ec807db44fa26
  Stored in directory: /home/ronald245/.cache/pip/wheels/f6/d8/ff/3c14a64b8f2ab1aa94ba2888f5a988be6ab446ec5c8d1a82da
Successfully built gpiod pure-pcapy3 frozenlist multidict
Installing collected packages: xmodem, pyserial, crccheck, voluptuous, typing-extensions, pyserial-asyncio, pure-pcapy3, multidict, gpiod, frozenlist, click-log, attrs, async-timeout, aiosqlite, yarl, aiosignal, cryptography, aiohttp, zigpy, bellows, silabs-flasher
Successfully installed aiohttp-3.9.1 aiosignal-1.3.1 aiosqlite-0.19.0 async-timeout-4.0.3 attrs-23.1.0 bellows-0.37.1 click-log-0.4.0 crccheck-1.3.0 cryptography-41.0.7 frozenlist-1.4.0 gpiod-2.1.3 multidict-6.0.4 pure-pcapy3-1.0.1 pyserial-3.5 pyserial-asyncio-0.6 silabs-flasher-0.0.3 typing-extensions-4.8.0 voluptuous-0.14.1 xmodem-0.4.7 yarl-1.9.3 zigpy-0.60.0
```

**Comment by RonaldPhilipsen** [comment]
I just noticed that when I change the requirements in the requirements.txt to either ~=  or == that solves the issue

**Comment by agners** [comment]
I've pinned it in the repository.

That being said, you should use [Universal Silicon Labs Flasher](https://github.com/NabuCasa/universal-silabs-flasher), it is better :smile:
